CREATE TABLE user_photos (
    id INT PRIMARY KEY IDENTITY(1,1),
    user_id INT NOT NULL,
    url NVARCHAR(255) NOT NULL,
    created_at DATETIMEOFFSET DEFAULT SYSDATETIMEOFFSET(),
    FOREIGN KEY (user_id) REFERENCES usuarios(id) ON DELETE CASCADE
);