import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "../styles/OfferList.css";
import ThemeRegistry from "../../lib/registry";
import NextAuthSessionProvider from '@/components/SessionProvider';
import RootClientLayout from '../components/layout/RootClientLayout'; // Import RootClientLayout

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <NextAuthSessionProvider>
          <ThemeRegistry>
            <RootClientLayout>{children}</RootClientLayout> {/* Use RootClientLayout */}
          </ThemeRegistry>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
